version: "2"
services:
  api:
    container_name: api
    restart: always
    build: .
    command: nodemon app.js
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    links:
      - database
  database:
    container_name: database
    image: mongo
    volumes:
      - ./:/data
    ports:
      - "27017:27017"
  database-seed:
    container_name: database-seed
    build: ./mongo-seed
    depends_on:
      - database
    links:
      - database
